spring.application.name=UserMS
server.port=8080
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/userms}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:27122004}

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
profilems.url=${PROFILEMS_URL:http://localhost:9000}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


USER_ALREADY_EXISTS= User Already Exists.
USER_NOT_FOUND= User Not Found.
INVALID_CREDENTIALS= Invalid Credentials.

